### PR TITLE
homePage  work done

### LINKED ISSUE #1: [feature] add home Page
do make the home page

### PR DESCRIPTION
**Pull request by Mohsin0473**
fixed #1

### CODE REVIEW

**Comment by mehran0466** [comment]
Good Work

**Comment by Khan8312** [comment]
in time .. keep it up

**Comment by AbshamAmir** [comment]
very good work

**Review by mehran0466 — APPROVED** [review]
Good Work

**Review by Khan8312 — APPROVED** [review]
all done

**Review by AbshamAmir — APPROVED** [review]
well done

**Pull request merged**
