### PR TITLE
PR: Merge Product Details page

### LINKED ISSUE #5: [feature] add Product Details Page

### PR DESCRIPTION
**Pull request by mehran0466**
Fixed #5

### CODE REVIEW

**Review by Khan8312 — APPROVED** [review]
Approved

**Review by Mohsin0473 — APPROVED** [review]
Good Work

**Comment by AbshamAmir** [comment]
nice work

**Review by AbshamAmir — APPROVED** [review]
keep it up

**Comment by mehran0466** [comment]
Fixed #8

**Comment by Khan8312** [comment]
appreciated

**Pull request merged**
